services:
  n8n:
    image: n8nio/n8n:1.121.3
    restart: always
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Taipei
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=your-password
      - N8N_USER_MANAGEMENT_DISABLED=true
      - N8N_SECURE_COOKIE=false

      # ğŸ‘‡ å¤–éƒ¨ URL ç›¸é—œåƒæ•¸
      - N8N_PORT=5678
      - WEBHOOK_URL=https://sparkly-knickknacky-ivory.ngrok-free.dev/
      - N8N_HOST=sparkly-knickknacky-ivory.ngrok-free.dev
      - N8N_PROTOCOL=https
      - N8N_SECURE_COOKIE=true

    volumes:
      - ./n8n_data:/home/node/.n8n

  ubuntu:
    build: ./ubuntu-cli # ğŸ‘ˆ ç”¨ä½ å‰›å‰›çš„ Dockerfile
    container_name: my-ubuntu-cli
    depends_on:
      - n8n # n8n å…ˆèµ·
    environment:
      # æ”¾åœ¨ .env ä¹Ÿå¯ä»¥ï¼šNGROK_AUTHTOKEN=...
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    volumes:
      # å·¥ä½œè³‡æ–™åŒ£ï¼šå®¹å™¨å…§ /home/ubuntu/demo å°æ‡‰åˆ°æœ¬æ©Ÿ
      - ./ubuntu_demo:/root/demo
      # ngrok è¨­å®šæª”ä¹ŸæŒä¹…åŒ–ï¼ˆä¸‹ä¸€æ¬¡ä¸ç”¨é‡è¨­ authtokenï¼‰
      - ./ngrok_config:/root/.config/ngrok
#  ollama:
#    image: ollama/ollama:latest
#    container_name: ollama
#    restart: always
#    ports:
#      - "11434:11434" # Web & API port
#    volumes:
#      - ./ollama_data:/root/.ollam_
